#!/usr/bin/env python3
"""Writes the wireframes of the native-first tactical rewrite (docs/plan/native-tactical.md, issue #316) to
assets/ui/mocks/tactical/*.rml. The style is assets/ui/mocks/tactical/mocks.rcss (hand written) on top of the live
HUD's own stylesheet (screens/tactical.rcss).

Unlike the Phase 5 mocks these do not redraw the HUD: tests/e2e/manual/native_tactical_mocks.lua opens each one over
the live Field Kit HUD in the real game, so a mock only adds what changes. Positions that point at HUD elements are in
dp measured on the live HUD at 1920x1080 (every 16:9 output shares them); data-anchor="<merc>" / "enemy<n>" places an
element over that soldier in the world (MockWorld.cc).

Run it after changing the mock data or layout:  python tools/ui/native_tactical_mocks.py
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "assets", "ui", "mocks", "tactical")

HEAD = """<rml>
<head>
	<title>{t} (native tactical wireframe)</title>
	<link type="text/rcss" href="../../components.rcss"/>
	<link type="text/rcss" href="../../screens/tactical.rcss"/>
	<link type="text/rcss" href="mocks.rcss"/>
</head>
<!-- Wireframe for docs/plan/native-tactical.md, drawn over the live tactical HUD in the real game
     (tests/e2e/manual/native_tactical_mocks.lua). Literal data. Generated by tools/ui/native_tactical_mocks.py:
     edit the generator, not this file. -->
<body class="t5 mock">
<div class="t5-root">
"""
FOOT = "</div>\n</body>\n</rml>\n"


def write(name, title, body):
    with open(os.path.join(OUT, name + ".rml"), "w", encoding="utf-8", newline="\n") as f:
        f.write(HEAD.format(t=title) + body + FOOT)


# ------------------------------------------------------------------ the live HUD at 1920x1080 (dp)
BODY_L = 254  # helmet, vest, belt, legs
BODY_R = 570  # face 1, face 2, LBE vest, pack
BODY_Y = [504, 578, 652, 726]
HANDS = [(254, 800), (498, 800)]  # 130 x 58
POCKET_X = [650, 714, 778, 842]  # 52 x 52
POCKET_Y = {"vest": 521, "belt": 605, "pack": 688}
CARDS = [82, 363, 644, 925]  # y 938, 273 x 130


def box(cls, x, y, w, h):
    return f'\t<div class="tgt {cls}" style="left: {x}dp; top: {y}dp; width: {w}dp; height: {h}dp;"></div>\n'


def pocket_targets(free_vest=(2, 3)):
    out = "".join(box("", x, y, 130, 58) for x, y in HANDS)
    out += "".join(box("", POCKET_X[i], POCKET_Y["vest"], 52, 52) for i in free_vest)
    for row in ("belt", "pack"):
        out += "".join(box("", x, POCKET_Y[row], 52, 52) for x in POCKET_X)
    return out


# ------------------------------------------------------------------ drag and drop (#320)
def drag_slot():
    body = "\t<!-- valid targets for a first aid kit: hands and every free pocket; worn-gear and LBE slots refuse it -->\n"
    body += pocket_targets()
    for y in BODY_Y[1:]:
        body += box("no", BODY_L, y, 58, 58)
    for y in BODY_Y:
        body += box("no", BODY_R, y, 58, 58)
    body += box("no hot", BODY_L, BODY_Y[0], 58, 58)
    body += """	<!-- the dragged item rides on the pointer at the slots' integer scale; the chip says what a release does -->
	<img class="ghost-item" src="nitem-201" style="left: 272dp; top: 522dp;"/>
	<img class="ptr" src="icon-drag" style="left: 262dp; top: 512dp;"/>
	<div class="chip2 no" style="left: 330dp; top: 448dp;">
		<span class="h">First aid kit → Helmet</span>
		<span class="why">Only headgear goes here</span>
		<span class="hint">Valid places are outlined · Right click puts it back</span>
	</div>
	<div class="foot-strip" style="left: 34dp; top: 872dp; width: 900dp;">
		<span class="kbd">Drag</span><span>move · onto a squad card: give · onto the world: drop or throw</span>
		<span class="kbd">Click</span><span>pick up / put down</span><span class="kbd">RMB</span><span>put back</span>
	</div>
"""
    write("drag_slot", "Drag and drop: a slot", body)


def drag_give():
    body = pocket_targets()
    body += f"""	<!-- squad cards are drop targets: in reach (gives; AP from the inventory core) or out of reach (says why) -->
	<div class="tgt card hot" style="left: {CARDS[1]}dp; top: 938dp; width: 273dp; height: 130dp;"></div>
	<div class="tgt card" style="left: {CARDS[2]}dp; top: 938dp; width: 273dp; height: 130dp;"></div>
	<div class="tgt card no" style="left: {CARDS[3]}dp; top: 938dp; width: 273dp; height: 130dp;"></div>
	<div class="tgt-tab" style="left: {CARDS[1]}dp; top: 904dp;"><img class="icon" src="icon-trade"/><span class="t">Give to Barry</span><span class="m">1 tile · 2 AP each</span></div>
	<div class="tgt-tab no" style="left: {CARDS[3]}dp; top: 904dp;"><img class="icon" src="icon-error"/><span class="t">Buns</span><span class="m">too far (9 tiles)</span></div>
	<img class="ghost-item" src="nitem-201" style="left: 510dp; top: 1000dp;"/>
	<img class="ptr" src="icon-drag" style="left: 500dp; top: 990dp;"/>
	<div class="foot-strip" style="left: 34dp; top: 872dp; width: 900dp;">
		<span class="kbd">Drop</span><span>on a card: give (into a free pocket, else the hands) · Esc / RMB: put back</span>
	</div>
"""
    write("drag_give", "Drag and drop: give to a merc", body)


def arc(who, x0, y0, x1, y1, lift, n=12):
    out = ""
    for i in range(1, n):
        t = i / n
        x = x0 + (x1 - x0) * t
        y = y0 + (y1 - y0) * t - lift * t * (1 - t)
        out += f'\t<div class="dot arc" data-anchor="{who}" data-dx="{x:.0f}" data-dy="{y:.0f}"></div>\n'
    return out


def drag_world():
    body = "\t<!-- over the world a held grenade becomes a throw (a drop at the feet on the merc's own tile) -->\n"
    body += arc("Ivan", 0, 40, 480, -10, 170)
    body += """	<div class="diamond warn" data-anchor="Ivan" data-dx="480" data-dy="-20"></div>
	<img class="ghost-item" src="nitem-135" data-anchor="Ivan" data-dx="486" data-dy="-58"/>
	<img class="ptr" src="icon-throw" data-anchor="Ivan" data-dx="500" data-dy="-44"/>
	<div class="chip2" data-anchor="Ivan" data-align="left" data-dx="524" data-dy="-70">
		<span class="h">Throw hand grenade</span>
		<div class="l"><span class="k">Range</span><span class="v">7 tiles</span></div>
		<div class="l"><span class="k">AP</span><span class="v ok">5 · 14 left</span></div>
		<div class="l"><span class="k">Lands</span><span class="v warn">± 1 tile</span></div>
		<span class="hint">Click on Ivan: drop at his feet · RMB: put back</span>
	</div>
"""
    write("drag_world", "Drag and drop: onto the world", body)


# ------------------------------------------------------------------ cursors (#318)
def cur(tone, name, legacy, icon=None, sm=None, ring=False, pips=0, dm=False):
    p = ""
    if ring:
        p += '<div class="rt"></div>'
    if icon:
        p += f'<img class="icon" src="icon-{icon}"/>'
    if sm:
        p += f'<img class="icon sm" src="icon-{sm}"/>'
    for i in range(pips):
        p += f'<div class="pip" style="left: {70 + i * 10}dp;"></div>'
    if dm:
        p += '<div class="dm"></div>'
    return f'<div class="cur {tone}"><div class="pic">{p}</div><span class="n">{name}</span><span class="s">{legacy}</span></div>'


def cursors():
    tiles = [
        cur("ok", "Walk", "MOVE_WALK · CONFIRM · ALL", "walk", dm=True),
        cur("ok", "Run", "MOVE_RUN · REALTIME", "run", dm=True),
        cur("ok", "Sneak", "MOVE_SWAT", "sneak", dm=True),
        cur("ok", "Crawl", "MOVE_PRONE", "stance-prone", dm=True),
        cur("ok", "Drive", "MOVE_VEHICLE", "vehicle", dm=True),
        cur("no", "No path", "CANNOT_MOVE", "error", dm=True),
        cur("foe", "Fire", "ACTION_SHOOT", ring=True, sm="target"),
        cur("foe", "Aim +2", "TARGETAIM1..9", ring=True, pips=2),
        cur("foe", "Burst", "TARGETBURST · CONFIRM", ring=True, sm="burst"),
        cur("foe", "Autofire", "(new: role-gated auto)", ring=True, sm="fast-forward"),
        cur("no", "No chance", "NOCHANCE · AIMCANT", ring=True, sm="error"),
        cur("warn", "Reloading", "TARGET_RELOADING", "reload"),
        cur("foe", "Punch", "PUNCH_GRAY / RED / AIM", "punch"),
        cur("foe", "Knife", "KNIFE_REG / HIT / AIM", "blade"),
        cur("ok", "Throw", "ACTION_TOSS", "throw"),
        cur("ok", "Launch", "ACTION_FLASH_TOSS", "launcher"),
        cur("no", "Out of reach", "ACTION_RED_TOSS", "throw"),
        cur("ok", "Bandage", "ACTION_FIRSTAID", "medkit"),
        cur("ok", "Pick up / use", "NORMAL / OKHANDCURSOR", "pointer"),
        cur("ok", "Open door", "ACTION_OPEN", "door"),
        cur("ok", "Talk", "TALK_A", "talk"),
        cur("warn", "Talk: too far", "TALK_OUT_RANGE", "talk"),
        cur("ok", "Give", "(catch / give)", "trade"),
        cur("ok", "Repair · use kit", "(item on item)", "repair"),
        cur("ok", "Climb", "(roof edge)", "climb"),
        cur("ok", "Jump over", "JUMP (fence)", "chevron-up"),
        cur("ok", "Look / turn", "LOOK", "look"),
        cur("ok", "Leave sector", "EXIT_N/S/E/W · GRID", "exit-sector"),
        cur("no", "Can't leave", "NOEXIT_N/S/E/W", "exit-sector"),
        cur("warn", "Busy", "(UI locked)", "wait"),
    ]
    body = f"""	<div class="sheet hud">
		<div class="hud-head"><img class="icon sm" src="icon-pointer"/><span class="t" style="margin-left: 8dp;">Tactical cursors</span><span class="m">one native pointer for every mode, at output resolution · small text: the legacy cursor ids it replaces</span></div>
		<div class="body">
			<div class="grid">{"".join(tiles)}</div>
			<div class="side">
				<span class="cap">Tone</span>
				<div class="tones"><span><span class="sw" style="background-color: #D9A54A;"></span>can do</span><span><span class="sw" style="background-color: #E0B040;"></span>with a catch</span><span><span class="sw" style="background-color: #B0442E;"></span>hostile / can't</span></div>
				<p>The shape says what a click does; the chip next to it says what it costs. Move cursors put a marker on the tile; the turn-based "confirm" click fills the marker instead of swapping bitmaps.</p>
				<span class="cap">Target chip</span>
				<div class="chip2 no"><span class="h">Fire at Soldier · torso</span><div class="l"><span class="k">Hit</span><span class="v">64 %</span></div><div class="l"><span class="k">AP</span><span class="v ok">6 · aim +2: 8</span></div><div class="l"><span class="k">Range</span><span class="v">14 tiles</span></div><span class="hint">RMB: aim more · B: burst</span></div>
				<span class="cap">Move chip</span>
				<div class="chip2"><span class="h">Run</span><div class="l"><span class="k">AP</span><span class="v ok">12 · 6 left</span></div><span class="hint">beyond this turn: amber path</span></div>
				<span class="cap">Interaction chip</span>
				<div class="chip2 warn"><span class="h">Door · locked</span><div class="l"><span class="k">Lockpick</span><span class="v">5 AP</span></div><span class="hint">click: the door menu</span></div>
			</div>
		</div>
	</div>
"""
    write("cursors", "Cursor sheet", body)


def target():
    body = """	<div class="ring foe" data-anchor="enemy0" data-dy="-6" style="width: 70dp; height: 70dp;"></div>
	<div class="ring foe thin" data-anchor="enemy0" data-dy="-16" style="width: 90dp; height: 90dp;"></div>
	<div class="chip2 no" data-anchor="enemy0" data-align="left" data-dx="56" data-dy="-24">
		<span class="h">Fire at Soldier · torso</span>
		<div class="l"><span class="k">Hit</span><span class="v">64 %</span></div>
		<div class="l"><span class="k">Aim</span><span class="v">●●○○ · +2 clicks</span></div>
		<div class="l"><span class="k">AP</span><span class="v ok">8 · 12 left</span></div>
		<div class="l"><span class="k">Range</span><span class="v">14 tiles · in range</span></div>
		<span class="hint">Click: fire · RMB: aim more · B: burst · Ctrl: aim at head / legs</span>
	</div>
"""
    write("target", "Target cursor and chip", body)


def move():
    now = [(0, 64), (40, 84), (80, 104), (120, 124), (160, 144), (200, 144), (240, 144)]
    later = [(280, 164), (320, 184)]
    body = "\t<!-- the path through the tile centres: solid for what this turn's AP buys, amber beyond -->\n"
    body += "".join(f'\t<div class="dot" data-anchor="Ivan" data-dx="{x}" data-dy="{y}"></div>\n' for x, y in now)
    body += "".join(f'\t<div class="dot far" data-anchor="Ivan" data-dx="{x}" data-dy="{y}"></div>\n' for x, y in later)
    body += """	<div class="diamond" data-anchor="Ivan" data-dx="240" data-dy="134"></div>
	<div class="diamond warn" data-anchor="Ivan" data-dx="360" data-dy="194"></div>
	<img class="ptr" src="icon-run" data-anchor="Ivan" data-dx="372" data-dy="168"/>
	<div class="chip2 warn" data-anchor="Ivan" data-align="left" data-dx="392" data-dy="160">
		<span class="h">Run to here</span>
		<div class="l"><span class="k">AP</span><span class="v warn">22 · 14 now, 8 next turn</span></div>
		<div class="l"><span class="k">Noise</span><span class="v">loud (running)</span></div>
		<span class="hint">solid: this turn · amber: next turn · click again: go</span>
	</div>
"""
    write("move", "Move path and cost", body)


# ------------------------------------------------------------------ popups (#321)
def stack():
    its = "".join(
        f'<div class="it{" on" if i == 2 else ""}"><div class="pc"><img class="pic" src="nitem-71"/></div>'
        f'<span class="v{" low" if v.startswith("9") else ""}">{v}</span></div>'
        for i, v in enumerate(["15/15", "15/15", "9/15", "15/15"]))
    body = box("hot", POCKET_X[0], POCKET_Y["vest"], 52, 52)
    body += f"""	<div class="mpop hud" id="tac.stack" style="left: 640dp; top: 214dp; width: 452dp;">
		<div class="hud-head"><img class="icon sm" src="icon-ammo"/><span class="t" style="margin-left: 8dp;">9 mm magazines</span><span class="m">4 in vest pocket 1</span><div class="grow"></div><button class="icon-btn" title="Close (Esc)"><img class="icon" src="icon-close"/></button></div>
		<div class="stk">{its}</div>
		<div class="split"><span class="k">Take</span><button class="icon-btn"><img class="icon sm" src="icon-remove"/></button><span class="n">2</span><button class="icon-btn"><img class="icon sm" src="icon-add"/></button><div class="grow"></div></div>
		<div class="foot"><button class="btn"><span class="label">Take one</span></button><button class="btn"><span class="label">Take 2</span></button><div class="grow"></div><button class="btn btn-primary"><span class="label">Take all</span></button></div>
		<span class="hint">Click a magazine to take that one · drag one onto a slot, a card or a gun to load it</span>
	</div>
"""
    write("stack", "Item stack popup", body)


def keyring():
    rows = [("Key: Drassen mine office", "D13 · found on day 4", 1, True),
            ("Key: San Mona warehouse", "C5 · from Angel", 1, False),
            ("Key: Omerta hideout", "A10 · from Fatima", 2, False)]
    kr = "".join(
        f'<div class="krow"><div class="pc"><img class="pic" src="nitem-271"/></div><div class="tx"><span class="a">{a}</span>'
        f'<span class="b">{b}</span></div><span class="q">×{q}</span>'
        f'<button class="btn{" is-disabled" if d else ""}" title="{"Point at a locked door first" if d else "Use on the door in front of Ivan"}"><span class="label">Use</span></button>'
        f'<button class="btn"><span class="label">Give</span></button></div>'
        for a, b, q, d in rows)
    body = box("hot", 774, 826, 73, 35)
    body += f"""	<div class="mpop hud" id="tac.keyring" style="left: 700dp; top: 556dp; width: 470dp;">
		<div class="hud-head"><img class="icon sm" src="icon-key"/><span class="t" style="margin-left: 8dp;">Key ring</span><span class="m">Ivan · sample keys</span><div class="grow"></div><button class="icon-btn" title="Close (K)"><img class="icon" src="icon-close"/></button></div>
		<div class="rows">{kr}</div>
		<div class="foot"><span class="hint" style="padding: 0;">Drag a key onto a door to use it, or onto a squad card to give it</span><div class="grow"></div><button class="btn"><span class="label">Close</span><span class="kbd">K</span></button></div>
	</div>
"""
    write("keyring", "Key ring popup", body)


def talk():
    body = """	<!-- the approved Phase 5 layout (centred over the bar, never over the speaker), in the Field Kit style -->
	<div class="talk hud" id="tac.talk">
		<div class="body">
			<div class="npc"><div class="face"><img class="pic" src="sface-63"/><img class="spk" src="icon-talk"/></div><span class="nm">Fatima</span><span class="rl">Omerta rebel · profile</span></div>
			<div class="say" id="tac.talk.text">
				<span class="who">Fatima</span>
				<span class="line">"You are the ones Enrico sent? Then take this letter to the rebels. They are hiding near here, and they will not trust you without it."</span>
				<span class="prev">Ivan (friendly): "We are here to help your people, miss."</span>
			</div>
		</div>
		<div class="opts" id="tac.talk.approaches">
			<button class="btn on" title="Friendly approach"><img class="icon" src="icon-ok"/><span class="label">Friendly</span><span class="kbd">1</span></button>
			<button class="btn" title="Direct approach"><img class="icon" src="icon-chevron-right"/><span class="label">Direct</span><span class="kbd">2</span></button>
			<button class="btn" title="Threaten"><img class="icon" src="icon-warning"/><span class="label">Threaten</span><span class="kbd">3</span></button>
			<button class="btn" title="Give: drag an item or money onto the face"><img class="icon" src="icon-trade"/><span class="label">Give</span><span class="kbd">4</span></button>
			<button class="btn is-disabled" title="She will not join"><img class="icon" src="icon-add"/><span class="label">Recruit</span><span class="kbd">5</span></button>
			<button class="btn" title="Ask to repeat"><img class="icon" src="icon-reload"/><span class="label">Come again?</span><span class="kbd">6</span></button>
			<div class="grow"></div>
			<button class="btn btn-primary" title="Stop talking"><span class="label">Done</span><span class="kbd">Esc</span></button>
		</div>
	</div>
	<div class="bubble" data-anchor="Ivan" data-dy="-96"><span class="who">Ivan</span><span class="tx">"Comrade, we will deliver your letter."</span></div>
"""
    write("talk", "NPC talk panel", body)


def exit_menu():
    body = """	<img class="ptr" src="icon-exit-sector" style="left: 1886dp; top: 500dp; image-color: #D9A54A;"/>
	<div class="mpop hud" id="tac.exit" style="left: 1440dp; top: 330dp; width: 430dp;">
		<div class="hud-head"><img class="icon sm" src="icon-exit-sector"/><span class="t" style="margin-left: 8dp;">Leave A9 → A10</span><span class="m">east edge</span><div class="grow"></div><button class="icon-btn" title="Cancel (Esc)"><img class="icon" src="icon-close"/></button></div>
		<div class="rows">
			<div class="opt on"><div class="rb"></div><span class="a">Squad 1</span><span class="b">4 mercs</span></div>
			<div class="opt"><div class="rb"></div><span class="a">Ivan only</span><span class="b">1 merc</span></div>
			<div class="opt off" title="Everyone in A9 is in squad 1"><div class="rb"></div><span class="a">Everyone in A9</span><span class="b">4 mercs</span></div>
		</div>
		<div class="chk"><div class="bx"></div><span>Load A10 now (otherwise they walk there on the map)</span></div>
		<div class="facts">
			<div class="kv"><span class="k">Travel</span><span class="v">on foot · arrive 07:52</span></div>
			<div class="kv"><span class="k">A10</span><span class="v">rebel hideout · no enemies known</span></div>
			<div class="kv"><span class="k">Left behind</span><span class="v">nobody</span></div>
		</div>
		<div class="foot"><div class="grow"></div><button class="btn"><span class="label">Cancel</span><span class="kbd">Esc</span></button><button class="btn btn-primary"><span class="label">Go</span><span class="kbd">Enter</span></button></div>
	</div>
"""
    write("exit", "Sector exit menu", body)


# ------------------------------------------------------------------ overhead map and placement (#323)
SQUAD = [("Ivan", 7, "Standing · MP5K 30/30"), ("Barry", 0, "Standing · Glock 6/6"),
         ("Grizzly", 3, "Standing · 9/9"), ("Buns", 17, "Stealth · 15/15")]


def who_rows(placed=None, sel="Ivan"):
    out = ""
    for n, f, s in SQUAD:
        if placed is None:
            st = f'<span class="st">{s}</span>'
        elif n in placed:
            st = '<span class="ok">placed</span>'
        else:
            st = f'<span class="wait">{"click the zone" if n == sel else "waiting"}</span>'
        cls = " sel" if n == sel else ""
        out += f'<div class="who{cls}"><div class="face"><img class="pic" src="sface-{f}"/></div><span class="nm">{n}</span>{st}</div>'
    return out


def map_panel(icon, title, sub, inner):
    return f"""	<div class="ovh-scrim"></div>
	<div class="ovh-map hud">
		<div class="hud-head"><img class="icon sm" src="icon-{icon}"/><span class="t" style="margin-left: 8dp;">{title}</span><span class="m">{sub}</span></div>
		<div class="well">
			<!-- stand-in picture: the legacy overhead (640 x 320) at 2x; the native one records the whole sector -->
			<img class="snap" src="overhead-snap" data-x="2" style="margin-left: -640dp; margin-top: -320dp;"/>
			<div class="mapbox">
{inner}			</div>
		</div>
	</div>
"""


def overhead():
    marks = """			<div class="mk us sel" style="left: 920dp; top: 136dp;"></div><div class="mk us" style="left: 940dp; top: 146dp;"></div><div class="mk us" style="left: 904dp; top: 152dp;"></div><div class="mk us" style="left: 930dp; top: 160dp;"></div>
			<div class="mk civ" style="left: 390dp; top: 74dp;"></div><div class="mk civ" style="left: 690dp; top: 354dp;"></div><div class="mk civ" style="left: 1050dp; top: 434dp;"></div>
			<div class="mk item" style="left: 550dp; top: 214dp;"></div><div class="mk item" style="left: 810dp; top: 284dp;"></div><div class="mk item" style="left: 290dp; top: 394dp;"></div>
			<div class="view" style="left: 750dp; top: 54dp; width: 360dp; height: 200dp;"></div>
			<span class="hov" style="left: 944dp; top: 104dp;">Ivan</span>
"""
    body = map_panel("map", "Overhead · A9 Omerta", "the whole sector · the box is the view", marks)
    body += f"""	<div class="ovh-side hud">
		<div class="hud-head"><span class="t">Sector</span><div class="grow"></div><span class="m">Day 1 · 07:00</span></div>
		<span class="sec cap">Legend</span>
		<div class="legend">
			<div class="lg"><span class="sw" style="background-color: #D9A54A;"></span><span class="a">Mercs</span><span class="n">4</span></div>
			<div class="lg"><span class="sw" style="background-color: #B0442E;"></span><span class="a">Enemies seen</span><span class="n">0</span></div>
			<div class="lg"><span class="sw" style="background-color: #A8916B;"></span><span class="a">Civilians</span><span class="n">3</span></div>
			<div class="lg"><span class="sw" style="background-color: #4F86A8; border-radius: 0;"></span><span class="a">Item piles</span><span class="n">3</span></div>
		</div>
		<span class="sec cap">Squad 1</span>
		{who_rows()}
		<div class="keys">
			<div class="ln"><span class="kbd">Click</span><span>centre the view there</span></div>
			<div class="ln"><span class="kbd">Hover</span><span>names · what is in a pile</span></div>
			<div class="ln"><span class="kbd">Insert</span><span class="kbd">Esc</span><span>back to the world</span></div>
		</div>
	</div>
"""
    write("overhead", "Overhead map", body)


def placement():
    marks = """			<div class="zone" style="left: 0; top: 0; width: 1280dp; height: 96dp;"></div>
			<div class="mk us" style="left: 520dp; top: 40dp;"></div><div class="mk us" style="left: 560dp; top: 56dp;"></div>
			<span class="hov" style="left: 640dp; top: 30dp;">Grizzly · click to place</span>
"""
    body = map_panel("destination", "Placement · A9 Omerta", "arriving from the north · place each merc in the lit zone", marks)
    body += f"""	<div class="ovh-side hud">
		<div class="hud-head"><span class="t">Arrival</span><div class="grow"></div><span class="m">2 of 4 placed</span></div>
		<div class="prog"><div class="fill" style="width: 50%;"></div></div>
		{who_rows(placed=("Ivan", "Barry"), sel="Grizzly")}
		<div class="btns">
			<button class="btn"><img class="icon" src="icon-remove"/><span class="label">Clear</span><span class="kbd">C</span></button>
			<button class="btn"><img class="icon" src="icon-squad"/><span class="label">Spread</span><span class="kbd">S</span></button>
			<button class="btn"><img class="icon" src="icon-player-group"/><span class="label">Group</span><span class="kbd">G</span></button>
			<button class="btn btn-primary is-disabled" title="Place everyone first"><span class="label">Done</span><span class="kbd">Enter</span></button>
		</div>
		<div class="keys">
			<div class="ln"><span class="kbd">Click</span><span>a merc, then the zone · drag a placed merc to move him</span></div>
		</div>
	</div>
"""
    write("placement", "Tactical placement", body)


# ------------------------------------------------------------------ world overlays (#322)
def overlays():
    body = """	<div class="ring" data-anchor="Barry" data-dy="-6" style="width: 76dp; height: 76dp;"></div>
	<div class="ring thin" data-anchor="Barry" data-dy="-20" style="width: 104dp; height: 104dp;"></div>
	<span class="callout" data-anchor="Barry" data-align="left" data-dx="64" data-dy="10">merc locator (/)</span>
	<div class="band" data-anchor="Ivan" data-dx="-30" data-dy="-36" style="width: 250dp; height: 160dp;"></div>
	<span class="callout" data-anchor="Ivan" data-dx="-30" data-dy="130">rubber-band selection</span>
	<div class="diamond" data-anchor="Ivan" data-dx="300" data-dy="150"></div>
	<div class="pool" data-anchor="Ivan" data-align="left" data-dx="330" data-dy="130">
		<div class="r"><div class="pc"><img class="pic" src="nitem-201" data-x="1"/></div><span class="a">First aid kit</span><span class="q">1</span></div>
		<div class="r"><div class="pc"><img class="pic" src="nitem-71" data-x="1"/></div><span class="a">9 mm magazine</span><span class="q">2</span></div>
		<div class="r"><div class="pc"><img class="pic" src="nitem-64" data-x="1"/></div><span class="a">Crowbar</span><span class="q">1</span></div>
		<span class="more">+2 more · click: the pick-up menu</span>
	</div>
	<span class="callout" data-anchor="Ivan" data-align="left" data-dx="330" data-dy="286">items under the cursor</span>
	<div class="flash" data-anchor="Ivan" data-dx="120" data-dy="300"><img class="icon" src="icon-sector-inventory"/></div>
	<span class="callout" data-anchor="Ivan" data-dx="120" data-dy="344">new item seen (pulses)</span>
	<span class="burst-x" data-anchor="Ivan" data-dx="760" data-dy="40">×</span><span class="burst-x" data-anchor="Ivan" data-dx="796" data-dy="58">×</span><span class="burst-x" data-anchor="Ivan" data-dx="776" data-dy="84">×</span>
	<span class="callout" data-anchor="Ivan" data-dx="780" data-dy="124">burst impacts</span>
	<div class="paused hud"><img class="icon" src="icon-pause"/><span class="t">Game paused</span><span class="kbd">Pause</span></div>
"""
    write("overlays", "World overlays", body)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for f in (drag_slot, drag_give, drag_world, cursors, target, move, stack, keyring, talk, exit_menu, overhead,
              placement, overlays):
        f()
    print("wrote", OUT)
