#!/usr/bin/env python3
"""Writes the Phase 7 intro/ending and victory-epilogue wireframes (M2, docs/ui/intro.md, docs/ui/epilogue.md) to
assets/ui/mocks/phase7/*.rml.

Literal data shaped like the end of a campaign (day 18, 41 sectors, 612 kills). Merc faces ("face-<n>") come from
the player's game data at runtime; nothing derived from the game art is written. Shown in game with
ja2.debug("mock", "phase7/<name>"); screenshots: tests/e2e/manual/phase7_mocks.lua.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'assets', 'ui', 'mocks', 'phase7')


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def icon(n, cls='icon'):
    return f'<img class="{cls}" src="icon-{n}"/>'


def kbd(k):
    return f'<span class="kbd">{k}</span>'


def btn(label, k=None, cls='btn', id=None, ic=None):
    i = f' id="{id}"' if id else ''
    return (f'<button class="{cls}"{i}>' + (icon(ic) if ic else '') + f'<span class="label">{label}</span>'
            + (kbd(k) if k else '') + '</button>')


def head(title, style):
    return f'''<rml>
<head>
	<title>{esc(title)} (Phase 7 wireframe)</title>
	<link type="text/rcss" href="../../components.rcss"/>
	<link type="text/rcss" href="phase7.rcss"/>
</head>
<!-- M2 wireframe (docs/ui/intro.md, docs/ui/epilogue.md). Literal data.
     Generated by tools/ui/phase7_mocks.py: edit the generator, not this file. -->'''


def chrome(scene, scenes, hint='Space / click — next scene · Esc — skip', progress=None):
    """The intro stage's fading hint bar: scene dots + position on the left, the skip hint on the right."""
    dots = ''.join(f'<span class="in-dot{" on" if i == scene else ""}"></span>' for i in range(scenes))
    track = (f'<div class="in-track"><div class="fill" style="width: {progress}%"></div></div>'
             if progress is not None else '')
    return f'''<div class="in-chrome" id="intro.chrome">
		<div class="in-scenes" id="intro.scenes">{dots}<span class="in-count">Scene {scene + 1} of {scenes}</span></div>
		<div class="in-hint">{esc(hint)}</div>
	</div>
	{track}'''


def intro_stage():
    return head('Intro stage', 'intro') + f'''
<body class="in">
<div class="in-stage">
	<div class="in-video"><span class="in-video-note">the video plays here (legacy layer, integer-scaled and centred)</span></div>
</div>
{chrome(1, 4, progress=42)}
</body>
</rml>
'''


def intro_fallback():
    return head('Intro still card', 'intro') + f'''
<body class="in">
<div class="in-stage">
	<div class="in-card" id="intro.card">
		<span class="in-card-count">Scene 2 of 4</span>
		<span class="in-card-note">video not available</span>
	</div>
</div>
{chrome(1, 4, hint='Space — next scene · Esc — skip', progress=0)}
</body>
</rml>
'''


# Those who came home / the fallen (name, profile id, nickname shown)
HOME = [('Fox', 0), ('Len', 2), ('Ivan', 5), ('Barry', 11), ('Livewire', 22), ('Meltdown', 38)]
FALLEN = [('Trevor', 4), ('Kyle', 17)]


def chips(people, dead=False):
    out = []
    for name, pid in people:
        badge = f'{icon("dead", "icon sm")}<span class="ep-badge">fallen</span>' if dead else ''
        fate = 'fell in Arulco' if dead else 'came home'
        out.append(f'<div class="ep-chip{" dead" if dead else ""} has-tip" id="epilogue.chip.{pid}">'
                   f'<span class="ep-face"><img src="face-{pid}"/></span>'
                   f'<span class="ep-name">{esc(name)}</span>{badge}'
                   f'<div class="tooltip"><div class="tip-title">{esc(name)}</div>'
                   f'<div class="tip-text">{esc(fate)}</div></div></div>')
    return '\n\t\t'.join(out)


def stat(value, label, sub=''):
    s = f'<span class="ep-sub">{esc(sub)}</span>' if sub else ''
    return (f'<div class="ep-stat"><span class="ep-num">{esc(value)}</span>'
            f'<span class="ep-label">{esc(label)}</span>{s}</div>')


def epilogue(with_fallen=True):
    fallen = ''
    if with_fallen:
        fallen = f'''
	<div class="ep-row">
		<div class="ep-row-head">The fallen</div>
		<div class="ep-chips">{chips(FALLEN, dead=True)}</div>
	</div>'''
    return head('Victory epilogue', 'epilogue') + f'''
<body class="ep">
<div class="ep-bg"></div>
<div class="ep-root">
<div class="ep-col">
	<div class="ep-head">
		<span class="ep-kicker" id="epilogue.title">Arulco is free</span>
		<span class="ep-sub" id="epilogue.sub">Deidranna is dead. The war is over.</span>
	</div>
	<p class="ep-text" id="epilogue.text">The occupation is over. What becomes of Arulco now is not decided by a
	bullet, but by the people who stayed when the world looked away.</p>
	<div class="ep-stats">
		{stat('18', 'days in arulco')}
		{stat('41', 'sectors liberated', 'of 256')}
		{stat('612', 'enemies killed', '21 admins · 402 troops · 189 elites')}
		{stat('9', 'mercs who served', 'of them 2 fell')}
	</div>
	<div class="ep-effort" id="epilogue.effort">
		<span class="ep-label">war effort</span>
		<div class="bar thick"><div class="fill" style="width: 78%"></div></div>
		<span class="ep-pct">78%</span>
	</div>
	<div class="ep-row">
		<div class="ep-row-head">Those who came home</div>
		<div class="ep-chips">{chips(HOME)}</div>
	</div>{fallen}
	<div class="ep-actions">
		{btn('Continue to credits', 'Enter', cls='btn btn-primary', id='epilogue.continue')}
		{btn('Main menu', 'Esc', cls='btn btn-ghost', id='epilogue.menu')}
	</div>
</div>
</div>
</body>
</rml>
'''


def write(name, text):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', os.path.relpath(path))


if __name__ == '__main__':
    write('intro_stage.rml', intro_stage())
    write('intro_fallback.rml', intro_fallback())
    write('epilogue.rml', epilogue(True))
    write('epilogue_clean.rml', epilogue(False))
