#!/usr/bin/env python3
"""Writes the Phase 5 wireframes of the native tactical HUD (M2, docs/ui/tactical.md) to
assets/ui/mocks/phase5/*.rml. The style is assets/ui/mocks/phase5/tactical.rcss (hand written).

The mocks are shown in the game over the real tactical world (tests/e2e/manual/phase5_mocks.lua):
- data-world="clear" on <body> hides the legacy HUD, so the whole world shows behind the mock;
- data-anchor="<merc>" puts the names, bars and menus over that merc in the world (MockWorld.cc);
- item pictures and faces come from the player's game data at an integer scale (nitem-, nitembig-, sface-).

Run it after changing the mock data or layout:  python tools/ui/phase5_mocks.py
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "assets", "ui", "mocks", "phase5")

# ------------------------------------------------------------------ the squad of the mock (Omerta, day 1)
# name, face, full name, hp, hpmax, energy, morale, ap (combat), hand item, ammo, ammo max, status icons, sub line
MERCS = [
    ("Ivan", 7, "Ivan Dolvich", 82, 88, 70, 66, 14, 26, 24, 30, [], "Standing"),
    ("Barry", 0, "Barry Unger", 61, 79, 48, 58, 9, 8, 5, 7, ["bleeding:danger"], "Crouched"),
    ("Grizzly", 3, "Steve Bornell", 95, 95, 77, 72, 18, 31, 2, 7, [], "Standing"),
    ("Buns", 17, "Monica Sondergaard", 66, 71, 81, 52, 0, 3, 4, 15, ["sneak:info"], "Stealth"),
]
SELECTED = "Ivan"


def e(s):
    return s.replace("&", "&amp;").replace("&amp;#", "&#")


def pic(kind, n, x=2, cls="pic"):
    """A game picture at an integer scale (MockWorld.cc sizes it): kind is nitem, nitembig or sface."""
    xs = "" if x == 2 else f' data-x="{x}"'
    return f'<img class="{cls}" src="{kind}-{n}"{xs}/>'


def doc(name, title, body, world=True, extra_rcss=""):
    w = ' data-world="clear"' if world else ""
    return f"""<rml>
<head>
	<title>{title} (Phase 5 wireframe)</title>
	<link type="text/rcss" href="../../components.rcss"/>
	<link type="text/rcss" href="tactical.rcss"/>{extra_rcss}
</head>
<!-- M2 wireframe of the native tactical HUD (docs/ui/tactical.md), shown over the real tactical world.
     Literal data. Generated by tools/ui/phase5_mocks.py: edit the generator, not this file. -->
<body class="t5"{w}>
<div class="t5-root" id="tac">
{body}
</div>
</body>
</rml>
"""


# ------------------------------------------------------------------ pieces
LOG = [
    ("08:14", "", "Ivan: \"Area looks clear, comrades.\"", "dialogue"),
    ("08:15", "", "Barry has picked up a first aid kit.", ""),
    ("08:16", "", "Grizzly is bleeding.", "combat"),
]


def log_lines(lines=LOG):
    out = []
    for i, (tm, _ic, tx, cls) in enumerate(lines):
        old = " old" if i == 0 and len(lines) > 2 else ""
        out.append(f'<div class="log-line {cls}{old}"><span class="tm">{tm}</span><span class="tx">{e(tx)}</span></div>')
    return f'<div class="log-lines audit-skip" id="tac.log.lines" title="Recent messages (L opens the log)">{"".join(out)}</div>'


def minimap(day="DAY 1", clock="08:16", foes=False):
    blds = [(18, 20, 60, 40), (96, 14, 40, 52), (170, 34, 70, 30), (40, 96, 54, 44), (130, 104, 46, 40), (210, 92, 60, 52)]
    roads = [(0, 76, 300, 10), (150, 0, 10, 176)]
    b = "".join(f'<div class="bld" style="left: {x}dp; top: {y}dp; width: {w}dp; height: {h}dp;"></div>' for x, y, w, h in blds)
    r = "".join(f'<div class="road" style="left: {x}dp; top: {y}dp; width: {w}dp; height: {h}dp;"></div>' for x, y, w, h in roads)
    dots = [(150, 120, "us sel"), (162, 128, "us"), (140, 132, "us"), (170, 116, "us"), (60, 60, "civ"), (230, 70, "mil")]
    if foes:
        dots += [(110, 40, "foe"), (250, 30, "foe")]
    d = "".join(f'<div class="dot {c}" style="left: {x}dp; top: {y}dp;"></div>' for x, y, c in dots)
    return f"""<div class="mini hud" id="tac.minimap">
		<div class="where"><span class="sec">A9</span><span class="town">Omerta</span><div class="grow"></div><span class="day">{day}</span><span class="clock">{clock}</span></div>
		<div class="radar" id="tac.minimap.map" title="Click to look there; drag to pan">{b}{r}<div class="view" style="left: 96dp; top: 70dp; width: 120dp; height: 76dp;"></div>{d}</div>
		<div class="mtools">
			<button class="icon-btn" id="tac.overhead" title="Overhead map (Insert)"><img class="icon" src="icon-map"/></button>
			<button class="icon-btn" id="tac.roofs" title="Show roofs and tree tops (T)"><img class="icon" src="icon-unexplored"/></button>
			<button class="icon-btn" id="tac.glow" title="Highlight items on the ground (I)"><img class="icon" src="icon-sector-inventory"/></button>
			<div class="legend"><div class="dot us"></div><span>Us</span><div class="dot foe"></div><span>Enemy</span><div class="dot mil"></div><span>Militia</span></div>
		</div>
	</div>"""


def card(m, combat=False, selected=False, done=False, cls=""):
    name, face, _full, hp, hpmax, en, mo, ap, item, am, ammax, icons, sub = m
    c = "tcard"
    if selected:
        c += " sel"
    if done:
        c += " done"
    if cls:
        c += " " + cls
    ic = ""
    for i in icons:
        n, k = i.split(":")
        ic += f'<img class="icon {k}" src="icon-{n}" title="{n.capitalize()}"/>'
    apv = f'<div class="ap"><span class="k">AP </span>{ap}</div>' if combat else ""
    spk = '<img class="spk" src="icon-talk"/>' if "talking" in cls else ""
    low = " low" if am * 3 < ammax else ""
    i = name.lower()
    return f"""<div class="{c}" id="tac.squad[{i}]" title="{name}: click to select, double-click for details (`)">
			<div class="face">{pic("sface", face)}{apv}{spk}</div>
			<div class="info">
				<div class="nr"><span class="nm">{name}</span>{ic}</div>
				<span class="sub">{sub}</span>
				<div class="st"><span class="k">HP</span><div class="bar hp"><div class="fill" style="width: {hp * 100 // 100}%"></div><div class="lost" style="width: {(hpmax - hp) * 100 // 100}%"></div></div><span class="v">{hp}</span></div>
				<div class="st"><span class="k">EN</span><div class="bar breath"><div class="fill" style="width: {en}%"></div></div><span class="v">{en}</span></div>
				<div class="st"><span class="k">MO</span><div class="bar morale"><div class="fill" style="width: {mo}%"></div></div><span class="v">{mo}</span></div>
				<div class="hand" id="tac.squad[{i}].hand" title="In hand: right-click for details">{pic("nitem", item, 1)}<span class="am{low}">{am}/{ammax}</span></div>
			</div>
		</div>"""


def squad_bar(combat=False, sel=SELECTED, done=(), extra_cls=None, empty=2):
    extra_cls = extra_cls or {}
    cards = "".join(card(m, combat, m[0] == sel, m[0] in done, extra_cls.get(m[0], "")) for m in MERCS)
    cards += "".join(f'<div class="tcard ghost"><span>Empty slot</span></div>' for _ in range(empty))
    squads = '<div class="sq on" id="tac.squadtab[1]" title="Squad 1 (1)"><span>1</span><span class="n">4</span></div>' \
             '<div class="sq" id="tac.squadtab[2]" title="Squad 2 (2)"><span>2</span><span class="n">2</span></div>' \
             '<div class="sq empty" id="tac.squadtab[3]" title="Squad 3 (3)"><span>3</span></div>' \
             '<div class="sq" id="tac.squadtab.next" title="Next squad (Shift+Space)"><img class="icon sm" src="icon-chevron-down"/></div>'

    def tb(i, icon, title, key, on=False, dis=False):
        c = "icon-btn" + (" on" if on else "") + (" is-disabled" if dis else "")
        return f'<button class="{c}" id="tac.{i}" title="{title} ({key})"><img class="icon" src="icon-{icon}"/><span class="kk">{key}</span></button>'
    tools = f"""<div class="tools" id="tac.tools">
			<div class="row">{tb("stance.stand", "stance-stand", "Stand", "S", on=True)}{tb("stance.crouch", "stance-crouch", "Crouch", "C")}{tb("stance.prone", "stance-prone", "Prone", "P")}<div class="sep"></div>{tb("move.run", "run", "Run", "R")}{tb("stealth", "sneak", "Stealth mode", "Z")}</div>
			<div class="row">{tb("burst", "burst", "Burst fire", "B")}{tb("look", "look", "Look / turn", "L")}{tb("talk", "talk", "Talk", "T")}<div class="sep"></div>{tb("climb", "climb", "Climb", "J")}{tb("level", "chevron-up", "View roof level", "Tab")}</div>
		</div>"""
    end_cls = "btn btn-primary" if combat else "btn is-disabled"
    end_title = "End your turn (D)" if combat else "Start turn-based combat (D)"
    end_label = "End turn" if combat else "Turn-based"
    sysb = f"""<div class="sys" id="tac.sys">
			<button class="{end_cls}" id="tac.endturn" title="{end_title}"><img class="icon" src="icon-end-turn"/><span class="label">{end_label}</span><span class="kbd">D</span></button>
			<button class="btn" id="tac.map" title="Strategic map (M)"><img class="icon" src="icon-map"/><span class="label">Map</span><span class="kbd">M</span></button>
			<div class="row"><button class="icon-btn" id="tac.inventory" title="Merc details and inventory (`)"><img class="icon" src="icon-inventory"/></button><button class="icon-btn" id="tac.log" title="Message log (L)"><img class="icon" src="icon-menu"/></button><button class="icon-btn last" id="tac.options" title="Options (O), save (Ctrl+S), load (Ctrl+L)"><img class="icon" src="icon-options"/></button></div>
		</div>"""
    return f"""<div class="sbar" id="tac.bar">
		<div class="squads" id="tac.squadtabs">{squads}</div>
		<div class="cards" id="tac.squad">{cards}</div>
		{tools}
		{sysb}
	</div>"""


def world_overlays(combat=False, sel=SELECTED, damage=None, target=False, path=None):
    out = []
    for m in MERCS:
        name, hp, hpmax, en, ap = m[0], m[3], m[4], m[5], m[7]
        c = "ov ov-merc" + (" sel" if name == sel else "")
        apv = f'<span class="apv">{ap} AP</span>' if combat and name == sel else ""
        out.append(f'<div class="{c} audit-skip" data-anchor="{name}" data-dy="-6"><span class="nm">{name}</span>'
                   f'<div class="bars"><div class="bar hp"><div class="fill" style="width: {hp * 100 // hpmax}%"></div></div>'
                   f'<div class="bar breath"><div class="fill" style="width: {en}%"></div></div></div>{apv}</div>')
    if damage:
        who, n = damage
        out.append(f'<div class="ov ov-dmg audit-skip" data-anchor="{who}" data-dx="44" data-dy="-36">&#8722;{n}</div>')
    if target:
        out.append('<div class="ov ov-target audit-skip" data-anchor="enemy0" data-dy="-30" title="Chance to hit, AP cost">'
                   '<img class="icon" src="icon-target"/><span class="k">Hit</span><span>62%</span><span class="k">AP</span><span>4</span></div>')
    if path:
        who, txt = path
        out.append(f'<div class="ov ov-path audit-skip" data-anchor="{who}" data-dx="150" data-dy="40">{txt}</div>')
    return "\n\t".join(out)


# ------------------------------------------------------------------ inventory pieces
def slot(item=None, cls="", lbl="", count=None, cond=None, ghost="face-gear", big=False, sid="", title="", att=False, x=2):
    c = "slot" + (" big" if big else "") + (" " + cls if cls else "")
    i = f' id="{sid}"' if sid else ""
    t = f' title="{title}"' if title else ""
    if item is None:
        inner = f'<img class="ghost" src="icon-{ghost}"/>'
    else:
        inner = f'<div class="item">{pic("nitem", item, x)}</div>'
        if count:
            inner += f'<span class="count">{count}</span>'
        if cond is not None:
            worn = " worn" if cond < 60 else ""
            inner += f'<div class="cond{worn}"><div class="fill" style="height: {cond}%"></div></div>'
        if att:
            inner += '<img class="att" src="icon-add" title="Has attachments"/>'
    if lbl:
        inner += f'<span class="lbl">{lbl}</span>'
    return f'<div class="{c}"{i}{t}>{inner}</div>'


def detail_panel(m=MERCS[0], drag=None, sel_slot=None, money_open=False):
    name, face, full, hp, hpmax, en, mo = m[0], m[1], m[2], m[3], m[4], m[5], m[6]
    attrs = [("Health", "82"), ("Agility", "77"), ("Dexterity", "68"), ("Strength", "80"), ("Leadership", "40"),
             ("Wisdom", "55"), ("Level", "4"), ("Marksmanship", "86"), ("Mechanical", "22"), ("Explosives", "35"),
             ("Medical", "18")]
    arows = "".join(f'<div class="row"><span class="k">{k}</span><span class="v{" up" if k == "Marksmanship" else ""}">{v}</span></div>' for k, v in attrs)
    ss = lambda k: "selected" if sel_slot == k else ""
    doll = f"""<div class="doll" id="tac.inv.body">
				<div class="col">
					<span class="cap">Head</span>
					{slot(211, lbl="Face 1", sid="tac.inv.head1", title="Face gear 1", cond=91)}
					{slot(None, lbl="Face 2", sid="tac.inv.head2", title="Face gear 2")}
					<span class="cap">Body</span>
					{slot(177, lbl="Helmet", sid="tac.inv.helmet", title="Kevlar helmet", cond=86)}
					{slot(164, lbl="Vest", sid="tac.inv.vest", title="Kevlar vest", cond=73)}
					{slot(None, lbl="Legs", sid="tac.inv.legs", title="Leggings", ghost="armour")}
				</div>
				<div class="col">
					<span class="cap">Hands</span>
					{slot(26, cls=ss("hand"), lbl="Hand", big=True, sid="tac.inv.hand", title="AKM: right-click for details", cond=89, count="24", att=True)}
					{slot(None, lbl="Off hand", big=True, sid="tac.inv.offhand", title="Second hand", ghost="gun")}
					<span class="cap">Kit</span>
					<div class="purse"><button class="btn" id="tac.inv.money" title="Split money"><img class="icon" src="icon-money"/><span class="label">Cash</span><span class="mono">$2,450</span></button></div>
					<div class="purse"><button class="btn" id="tac.inv.keys" title="Key ring (K)"><img class="icon" src="icon-key"/><span class="label">Keys</span><span class="mono">2</span></button></div>
				</div>
			</div>"""
    big = [(97, "3"), (None, None), (209, None), (None, None)]
    small = [(94 if False else 92, "2"), (135, "3"), (201, None), (203, None), (214, None), (131, None), (None, None), (None, None)]
    bigs = "".join(slot(it, big=True, lbl="Pocket", sid=f"tac.inv.big[{i}]", count=c, cond=95 if it else None, ghost="inventory",
                        cls=("drop-ok" if drag and i == 1 else ""))
                   for i, (it, c) in enumerate(big))
    smalls = "".join(slot(it, lbl="", sid=f"tac.inv.small[{i}]", count=c, cond=80 + i * 2 if it else None, ghost="inventory",
                          cls=("dragging" if drag and i == 0 else ""))
                     for i, (it, c) in enumerate(small))
    pockets = f"""<div class="pockets" id="tac.inv.pockets">
				<span class="cap">Big pockets</span><div class="grid">{bigs}</div>
				<span class="cap">Small pockets</span><div class="grid">{smalls}</div>
				<div class="kv"><span class="k">Weight carried</span><span class="v">14.6 / 26 kg</span></div>
				<div class="kv"><span class="k">Camouflage &#183; armour</span><span class="v">0% &#183; 31</span></div>
			</div>"""
    vit = f"""<div class="vit">
				<div class="stat"><span class="k">HP</span><span class="bar hp"><span class="fill" style="width: {hp}%"></span><span class="lost" style="width: {hpmax - hp}%"></span></span><span class="v">{hp}/{hpmax}</span></div>
				<div class="stat"><span class="k">EN</span><span class="bar breath"><span class="fill" style="width: {en}%"></span></span><span class="v">{en}</span></div>
				<div class="stat"><span class="k">MO</span><span class="bar morale"><span class="fill" style="width: {mo}%"></span></span><span class="v">Good</span></div>
			</div>"""
    return f"""<div class="detail hud" id="tac.detail">
		<div class="who">
			<div class="face">{pic("sface", face)}</div>
			<div class="names"><span class="nm">{name}</span><span class="full">{full} &#183; level 4 &#183; Squad 1</span>
				<div class="tags"><div class="tag"><img class="icon" src="icon-contract"/><span>Contract: 13 days</span></div><div class="tag"><img class="icon" src="icon-stance-stand"/><span>Standing &#183; walking</span></div><div class="tag warn"><img class="icon" src="icon-fatigue"/><span>Tired</span></div></div>
			</div>
			{vit}
			<div class="acts">
				<button class="icon-btn" id="tac.detail.close" title="Close (` or Esc)"><img class="icon" src="icon-close"/></button>
				<button class="icon-btn" id="tac.detail.mute" title="Mute this merc's speech"><img class="icon" src="icon-talk"/></button>
			</div>
		</div>
		<div class="body">
			<div class="attrs" id="tac.detail.attrs"><span class="cap" style="margin-top: 0;">Attributes</span>{arows}</div>
			{doll}
			{pockets}
		</div>
		<div class="foot"><span class="kbd">Drag</span><span>move &#183; onto a squad card: give &#183; onto the world: drop</span><span class="kbd">RMB</span><span>details</span><span class="kbd">Ctrl+Q</span><span>swap hands</span><span class="kbd">&#8592;</span><span class="kbd">&#8594;</span><span>other merc</span></div>
	</div>"""


def write(name, title, body, **kw):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name + ".rml"), "w", encoding="utf8", newline="\n") as f:
        f.write(doc(name, title, body, **kw))


# ------------------------------------------------------------------ the states
def squadbar():
    body = "\n\t".join([world_overlays(path=None), log_lines(), minimap(), squad_bar()])
    write("squadbar", "Tactical: squad bar, realtime", body)


def combat():
    lines = [("08:21", "", "Enemy spotted by Grizzly!", "combat"), ("08:21", "", "Ivan fires at a soldier: hit for 18.", "combat"),
             ("08:21", "", "Barry was hit (7)!", "combat")]
    banner = """<div class="banner" id="tac.turn"><div class="pill"><img class="icon" src="icon-action-points"/><span class="t">Your turn</span><span class="m">Round <b>3</b> &#183; 2 of 4 mercs have AP left</span></div></div>"""
    body = "\n\t".join([world_overlays(combat=True, damage=("Barry", 7), target=True), log_lines(lines), banner,
                        minimap(clock="08:21", foes=True), squad_bar(combat=True, done=("Buns",), extra_cls={"Barry": "crit"})])
    write("combat", "Tactical: squad bar in combat", body)


def inventory():
    drag = """<div class="drag-ghost audit-skip" style="left: 572dp; top: 418dp;">""" + pic("nitem", 92) + """</div>
	<div class="drag-tip audit-skip" style="left: 572dp; top: 474dp;">Into Ivan's big pocket &#183; 2 &#215; 5.45 mm AP</div>"""
    body = "\n\t".join([world_overlays(), squad_bar(), detail_panel(drag=True), drag])
    write("inventory", "Tactical: merc details and inventory, dragging", body)


def itemdesc():
    stats = [("Damage", "30"), ("Range", "40 tiles"), ("AP to fire", "5"), ("Burst (3)", "8 AP"), ("AP to reload", "4"), ("Weight", "4.3 kg")]
    srows = "".join(f'<div class="kv"><span class="k">{k}</span><span class="v">{v}</span></div>' for k, v in stats)
    atts = "".join([
        slot(241, sid="tac.desc.att[0]", title="Laser scope", cond=94),
        slot(None, sid="tac.desc.att[1]", title="Empty: drop an attachment", ghost="add", cls="drop-ok"),
        slot(None, sid="tac.desc.att[2]", title="Empty", ghost="add"),
        slot(None, sid="tac.desc.att[3]", title="Empty", ghost="add"),
    ])
    desc = f"""<div class="idesc hud" id="tac.desc">
		<div class="hud-head"><img class="icon sm" src="icon-gun"/><span class="t" style="margin-left: 8dp;">AKM</span><span class="m">Assault rifle &#183; 7.62 mm WP</span><div class="grow"></div>
			<button class="icon-btn" id="tac.desc.close" title="Close (Esc or right-click)"><img class="icon" src="icon-close"/></button></div>
		<div class="pic-area" id="tac.desc.picture">{pic("nitembig", 26)}</div>
		<span class="text">A reliable and inexpensive Soviet-designed assault rifle. It's been manufactured in many countries and is easy to maintain.</span>
		<div class="cols">
			<div class="c">
				<span class="cap">Weapon</span>{srows}
				<div class="cond-row"><span class="k">Condition</span><div class="bar ok"><div class="fill" style="width: 89%"></div></div><span class="v">89%</span></div>
			</div>
			<div class="c last">
				<span class="cap">Ammo</span>
				<div class="ammo" id="tac.desc.ammo">{slot(97, sid="tac.desc.mag", title="Magazine: drag out to unload")}<div class="a"><span class="n">24 / 30</span><span class="t">7.62 mm WP AP</span></div>
					<button class="btn" id="tac.desc.unload" title="Take the magazine out"><img class="icon sm" src="icon-reload"/><span class="label">Unload</span></button></div>
				<span class="cap">Attachments</span>
				<div class="atts" id="tac.desc.atts">{atts}</div>
				<span class="fits">Fits: laser scope, sniper scope, silencer, bipod, under-barrel launcher, barrel extender</span>
			</div>
		</div>
		<div class="pc"><span class="k pro">Pros</span><span class="v">Cheap ammo &#183; reliable</span></div>
		<div class="pc"><span class="k con">Cons</span><span class="v">Inaccurate at long range</span></div>
		<div class="foot"><span class="h">Drag an attachment onto a free slot; Ctrl+click an attachment to remove it.</span><div class="grow"></div>
			<button class="btn btn-primary" id="tac.desc.done"><span class="label">Done</span><span class="kbd">Esc</span></button></div>
	</div>"""
    drag = """<div class="drag-ghost audit-skip" style="left: 1428dp; top: 716dp;">""" + pic("nitem", 207) + """</div>
	<div class="drag-tip audit-skip" style="left: 1300dp; top: 672dp;">Attach silencer &#183; 2 AP</div>"""
    body = "\n\t".join([world_overlays(), squad_bar(), detail_panel(sel_slot="hand"), desc, drag])
    write("itemdesc", "Tactical: item description with attachments", body)


def money():
    pop = """<div class="pop money hud" id="tac.money" style="left: 446dp; bottom: 270dp;">
		<div class="hud-head"><img class="icon sm" src="icon-money"/><span class="t" style="margin-left: 8dp;">Split money</span><div class="grow"></div><button class="icon-btn" id="tac.money.close" title="Cancel (Esc)"><img class="icon" src="icon-close"/></button></div>
		<div class="amt" id="tac.money.amount"><span>$500</span><span class="of">of $2,450</span></div>
		<div class="chips"><button class="btn" id="tac.money.add1000">+1000</button><button class="btn" id="tac.money.add100">+100</button><button class="btn" id="tac.money.add10">+10</button><button class="btn" id="tac.money.add1">+1</button><button class="btn" id="tac.money.all">All</button><button class="btn" id="tac.money.clear">Clear</button></div>
		<span class="note">Type an amount or use the buttons. The split is put in your hand: drop it on a merc, a pocket or the ground.</span>
		<div class="modal-foot"><button class="btn" id="tac.money.cancel"><span class="label">Cancel</span><span class="kbd">Esc</span></button><button class="btn btn-primary" id="tac.money.take"><span class="label">Take $500</span><span class="kbd">Enter</span></button></div>
	</div>"""
    body = "\n\t".join([world_overlays(), squad_bar(), detail_panel(), pop])
    write("money", "Tactical: money split", body)


def menus():
    def mi(icon, label, key="", ap="", dis=False, cls="", why=""):
        c = "menu-item" + (" is-disabled" if dis else "") + (" " + cls if cls else "")
        k = f'<span class="kbd">{key}</span>' if key else ""
        a = f'<span class="ap">{ap}</span>' if ap else ""
        w = f'<span class="why">{why}</span>' if why else ""
        return f'<div class="{c}"><img class="icon" src="icon-{icon}"/><span class="label">{label}</span>{a}{k}</div>{w}'
    action = f"""<div class="pop menu audit-skip" id="tac.actionmenu" data-anchor="Ivan" data-dx="70" data-dy="0" data-align="left">
		<div class="menu-title"><span class="t">Ivan</span><span class="m">14 AP</span></div>
		<div class="menu-head">Move</div>
		{mi("walk", "Walk", "S")}{mi("run", "Run", "R")}{mi("sneak", "Crouched move", "C")}{mi("stance-prone", "Crawl", "P")}
		<div class="menu-sep"></div>
		<div class="menu-head">Act</div>
		{mi("gun", "Use firearm", "", "5 AP")}{mi("look", "Look", "L")}{mi("talk", "Talk", "T")}{mi("pointer", "Examine / handle", "Ctrl")}
		<div class="menu-sep"></div>
		{mi("close", "Cancel", "Esc")}
	</div>"""
    door = f"""<div class="pop menu audit-skip" id="tac.doormenu" style="left: 1240dp; top: 330dp;">
		<div class="menu-title"><span class="t">Door</span><span class="m">Barry &#183; 16 AP</span></div>
		{mi("door", "Open", "", "3 AP")}
		{mi("search", "Examine for traps", "", "5 AP")}
		{mi("wire-cut", "Untrap", "", "10 AP", dis=True, why="No trap found yet")}
		<div class="menu-sep"></div>
		{mi("key", "Unlock with key", "", "5 AP", dis=True, why="No key for this door")}
		{mi("toolkit", "Pick the lock", "", "8 AP", dis=True, why="Needs a lockpick kit")}
		{mi("stab", "Use crowbar", "", "10 AP")}
		{mi("punch", "Force open", "", "10 AP")}
		{mi("bomb", "Use explosive", "", "10 AP", dis=True, why="No shaped charge")}
		<div class="menu-sep"></div>
		{mi("close", "Cancel", "Esc")}
	</div>"""
    rows = [(26, "AKM", "", True), (97, "7.62 mm WP clip", "&#215;2", True), (201, "First aid kit", "", False), (219, "Money", "$140", True)]
    prow = "".join(f'<div class="row{" on" if on else ""}" id="tac.pickup[{i}]"><div class="chk{" on" if on else ""}">{"<img class=" + chr(34) + "icon" + chr(34) + " src=" + chr(34) + "icon-confirm" + chr(34) + "/>" if on else ""}</div>'
                   f'<div class="pbox">{pic("nitem", it)}</div><span class="n">{n}</span><span class="q">{q}</span></div>'
                   for i, (it, n, q, on) in enumerate(rows))
    pick = f"""<div class="pop pick hud audit-skip" id="tac.pickup" style="left: 760dp; top: 470dp;">
		<div class="hud-head"><img class="icon sm" src="icon-sector-inventory"/><span class="t" style="margin-left: 8dp;">Pick up</span><span class="m">Buns &#183; 4 items here</span></div>
		{prow}
		<div class="pick-foot foot"><button class="btn" id="tac.pickup.all"><span class="label">All</span><span class="kbd">A</span></button><div class="grow"></div><button class="btn" id="tac.pickup.cancel"><span class="label">Cancel</span></button><button class="btn btn-primary" id="tac.pickup.ok"><span class="label">Take 3</span><span class="kbd">Enter</span></button></div>
	</div>"""
    body = "\n\t".join([world_overlays(), log_lines(), minimap(), squad_bar(), action, door, pick])
    write("menus", "Tactical: action, door and pick-up menus", body)


def dialogue():
    talk = f"""<div class="talk hud" id="tac.talk">
		<div class="body">
			<div class="npc"><div class="face">{pic("sface", 63)}</div><span class="nm">Fatima</span><span class="rl">Omerta rebel</span></div>
			<div class="say" id="tac.talk.text">
				<span class="who">Fatima</span>
				<span class="line">"You are the ones Enrico sent? Then take this letter to the rebels. They are hiding near here, and they will not trust you without it."</span>
				<span class="prev">Ivan (friendly): "We are here to help your people, miss."</span>
			</div>
		</div>
		<div class="opts" id="tac.talk.approaches">
			<button class="btn on" id="tac.talk.friendly" title="Friendly approach"><img class="icon" src="icon-ok"/><span class="label">Friendly</span><span class="kbd">1</span></button>
			<button class="btn" id="tac.talk.direct" title="Direct approach"><img class="icon" src="icon-chevron-right"/><span class="label">Direct</span><span class="kbd">2</span></button>
			<button class="btn" id="tac.talk.threaten" title="Threaten"><img class="icon" src="icon-warning"/><span class="label">Threaten</span><span class="kbd">3</span></button>
			<button class="btn" id="tac.talk.give" title="Give: drag an item or money onto the face"><img class="icon" src="icon-trade"/><span class="label">Give</span><span class="kbd">4</span></button>
			<button class="btn is-disabled" id="tac.talk.recruit" title="Recruit (she will not join)"><img class="icon" src="icon-add"/><span class="label">Recruit</span><span class="kbd">5</span></button>
			<button class="btn" id="tac.talk.again" title="Ask to repeat"><img class="icon" src="icon-reload"/><span class="label">Come again?</span><span class="kbd">6</span></button>
			<div class="grow"></div>
			<button class="btn btn-primary" id="tac.talk.done" title="Stop talking"><span class="label">Done</span><span class="kbd">Esc</span></button>
		</div>
	</div>"""
    bubble = """<div class="ov bubble audit-skip" data-anchor="Ivan" data-dy="-80" id="tac.subtitle"><span class="who">Ivan</span><span class="tx">"Comrade, we will deliver your letter."</span></div>"""
    body = "\n\t".join([world_overlays(), minimap(), squad_bar(extra_cls={"Ivan": "talking"}), talk, bubble])
    write("dialogue", "Tactical: talking with an NPC", body)


def msglog():
    lines = [
        ("08:02", "info", "Squad 1 has arrived in sector A9.", "", False),
        ("08:03", "talk", "Ivan: \"Comrades, we begin.\"", "dialogue", False),
        ("08:09", "ok", "Barry has picked up a first aid kit.", "ok", False),
        ("08:12", "info", "Game saved: Quick save.", "", False),
        ("08:17", "warning", "Enemy spotted by Grizzly!", "combat", False),
        ("08:17", "info", "Turn-based combat started.", "", False),
        ("08:18", "error", "Ivan fires at a soldier: hit for 18.", "combat", False),
        ("08:18", "error", "Ivan fires at a soldier: missed.", "combat", False),
        ("08:19", "warning", "Barry was hit (7)! Barry is bleeding.", "combat", False),
        ("08:19", "talk", "Barry: \"I am hit!\"", "dialogue", False),
        ("08:20", "info", "Buns is out of action points.", "", False),
        ("08:21", "warning", "INTERRUPT! Ivan spotted a soldier at the corner.", "combat", True),
        ("08:21", "talk", "Ivan: \"There! By the wall!\"", "dialogue", True),
    ]
    ln = "".join(f'<div class="ln {c}{" new" if n else ""}"><span class="tm">{t}</span><img class="icon" src="icon-{ic}"/><span class="tx">{e(x)}</span></div>' for t, ic, x, c, n in lines)
    panel = f"""<div class="logp hud" id="tac.logpanel">
		<div class="hud-head"><img class="icon sm" src="icon-menu"/><span class="t" style="margin-left: 8dp;">Message log</span><span class="m">Day 1 &#183; 112 messages</span><div class="grow"></div>
			<button class="icon-btn" id="tac.logpanel.pin" title="Keep open"><img class="icon" src="icon-lock"/></button>
			<button class="icon-btn" id="tac.logpanel.close" title="Close (L or Esc)"><img class="icon" src="icon-close"/></button></div>
		<div class="filters"><div class="chip on" id="tac.log.all"><span>All</span><span class="n">112</span></div><div class="chip" id="tac.log.combat"><span>Combat</span><span class="n">41</span></div><div class="chip" id="tac.log.dialogue"><span>Speech</span><span class="n">23</span></div><div class="chip" id="tac.log.system"><span>System</span><span class="n">48</span></div></div>
		<div class="list scroll" id="tac.log.list">{ln}</div>
		<div class="foot"><span class="kbd">Wheel</span><span>scroll</span><span class="kbd">F12</span><span>clear the lines on screen</span><span class="kbd">Ctrl+F12</span><span>clear the log</span></div>
	</div>"""
    banner = """<div class="banner" id="tac.turn"><div class="pill int"><img class="icon" src="icon-warning"/><span class="t">Interrupt</span><span class="m"><b>Ivan</b> spotted a soldier &#183; your move</span></div></div>"""
    body = "\n\t".join([world_overlays(combat=True), panel, banner, minimap(clock="08:21", foes=True), squad_bar(combat=True, done=("Buns",))])
    write("msglog", "Tactical: message log and interrupt banner", body)


def enemy_turn():
    banner = """<div class="banner" id="tac.turn"><div class="pill foe"><img class="icon" src="icon-enemy"/><span class="t">Enemy turn</span><span class="m">4 soldiers moving</span><div class="prog"><div class="fill" style="width: 45%"></div></div></div></div>"""
    return banner


MAP = '<div class="ovh-bg"></div><div class="ovh-map hud" id="tac.overhead.map"><img src="overhead-snap"/></div>'


def overhead():
    left = f"""<div class="ovh-side l hud" id="tac.overhead.info">
		<div class="sect"><span class="cap">Overhead map</span><span class="big">A9 &#183; Omerta</span><span class="sm">Day 1, 08:16 &#183; town, 3 buildings searched</span></div>
		<div class="sect"><span class="cap">Legend</span>
			<div class="lg"><div class="dot us sel"></div><span>Selected merc</span></div>
			<div class="lg"><div class="dot us"></div><span>Our mercs</span><span class="n">4</span></div>
			<div class="lg"><div class="dot foe"></div><span>Enemies seen</span><span class="n">2</span></div>
			<div class="lg"><div class="dot mil"></div><span>Militia</span><span class="n">0</span></div>
			<div class="lg"><div class="dot civ"></div><span>Civilians</span><span class="n">5</span></div>
			<div class="lg"><div class="sw" style="background-color: #F2B33D;"></div><span>Items on the ground</span><span class="n">7</span></div>
		</div>
		<div class="sect"><span class="cap">Squad 1</span>
			{"".join(f'<div class="row{" sel" if m[0] == SELECTED else ""}" id="tac.overhead.merc[{m[0].lower()}]"><div class="face">{pic("sface", m[1], 1)}</div><span class="nm">{m[0]}</span></div>' for m in MERCS)}
		</div>
		<div class="foot"><button class="btn btn-primary" id="tac.overhead.close"><img class="icon" src="icon-close"/><span class="label">Back to the world</span><span class="kbd">Ins</span></button>
			<span class="sm">Click: centre the world there &#183; right-click: back</span></div>
	</div>"""
    tip = """<div class="ovh-tip audit-skip" style="left: 980dp; top: 520dp;">Grizzly &#183; standing &#183; HP 95</div>"""
    body = "\n\t".join([MAP, left, tip])
    write("overhead", "Tactical: overhead map", body, world=False)


def placement():
    rows = [("Ivan", 7, "ok"), ("Barry", 0, "ok"), ("Grizzly", 3, "todo sel"), ("Buns", 17, "todo")]
    rr = "".join(f'<div class="row {c}" id="tac.place.merc[{n.lower()}]"><div class="face">{pic("sface", f, 1)}</div><span class="nm">{n}</span>'
                 f'<img class="icon" src="icon-{"ok" if c == "ok" else "destination"}"/></div>' for n, f, c in rows)
    left = f"""<div class="ovh-side l hud" id="tac.place">
		<div class="sect"><span class="cap">Placement &#183; entering from the north</span><span class="big">A9 &#183; Omerta</span><span class="sm">Place your mercs in the highlighted part of the map. 2 of 4 placed.</span></div>
		<div class="sect"><span class="cap">Mercs</span>{rr}<span class="sm">Click a merc, then click the map; drag a placed merc to move him.</span></div>
		<div class="foot">
			<div class="btns2"><button class="btn" id="tac.place.clear" title="Clear all positions"><span class="label">Clear</span><span class="kbd">C</span></button><button class="btn" id="tac.place.spread" title="Spread the mercs out at random"><span class="label">Spread</span><span class="kbd">S</span></button><button class="btn last" id="tac.place.group" title="Place them as a group"><span class="label">Group</span><span class="kbd">G</span></button></div>
			<button class="btn btn-primary is-disabled" id="tac.place.done" title="Place every merc first"><img class="icon" src="icon-confirm"/><span class="label">Start the battle</span><span class="kbd">Enter</span></button>
		</div>
	</div>"""
    note = """<div class="zone-note"><div class="banner" style="position: relative; top: 0;"><div class="pill int"><img class="icon" src="icon-destination"/><span class="t">Place Grizzly</span><span class="m">click inside the highlighted zone</span></div></div></div>"""
    body = "\n\t".join([MAP, left, note])
    write("placement", "Tactical: placement", body, world=False)


if __name__ == "__main__":
    for f in (squadbar, combat, inventory, itemdesc, money, menus, dialogue, msglog, overhead, placement):
        f()
    print("wrote", OUT)
