package.path = (debug.getinfo(1, "S").source:match("^@(.*[/\\])") or "") .. "../?.lua;" .. package.path
local campaign = require("lib.campaign")
campaign.newGame()
campaign.hireFromAim("Ivan", "One Week", true)
campaign.landInArulco()
ja2.waitIdle()
ja2.setVideo{ res = "1920x1080", uiscale = 1, worldzoom = 2 }
ja2.waitIdle()
ja2.key("`")
ja2.waitIdle()
ja2.debug("keys", { keys = { 1, 2, 3, 3 } })
ja2.waitIdle()
ja2.click{ id = "tac.inv.keys" }
ja2.waitIdle()
ja2.log("popup=" .. ja2.popup().kind)
local r = ja2.popupOp("keyring", { action = "use", slot = 0 })
ja2.log("use: ok=" .. tostring(r.ok) .. " why=" .. tostring(r.why))
r = ja2.popupOp("keyring", { action = "take", slot = 0 })
ja2.log("take: ok=" .. tostring(r.ok) .. " why=" .. tostring(r.why))
ja2.waitIdle()
ja2.log("popup=" .. ja2.popup().kind)
ja2.log("hand=" .. tostring(ja2.inventory().hand and ja2.inventory().hand.item))
r = ja2.popupOp("key_on_door", { grid = 0 })
ja2.log("key_on_door: ok=" .. tostring(r.ok) .. " why=" .. tostring(r.why))
ja2.key("escape")
ja2.waitIdle()
ja2.log("hand after esc=" .. tostring(ja2.inventory().hand and ja2.inventory().hand.item))
