"""Writes a SPIR-V binary as a C header: embed.py <in.spv> <out.h>. Used by build.sh."""
import os
import sys

src, dst = sys.argv[1], sys.argv[2]
data = open(src, "rb").read()
name = os.path.basename(src)[: -len(".spv")].replace(".", "_")
with open(dst, "w", newline="\n") as f:
    f.write("// Generated by tools/shaders/build.sh from %s. Do not edit.\n" % os.path.basename(src)[: -len(".spv")])
    f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
    f.write("alignas(4) static const uint8_t %s_spv[] = {\n" % name)
    for i in range(0, len(data), 16):
        f.write("\t" + ", ".join("0x%02x" % b for b in data[i : i + 16]) + ",\n")
    f.write("};\nstatic const size_t %s_spv_size = sizeof(%s_spv);\n" % (name, name))
