"""Writes shader binaries as one C header: embed.py <out.h> <source name> <symbol>=<file> ...
Text files (.metal) get a terminating zero. Used by build.sh."""
import sys

out, source = sys.argv[1], sys.argv[2]
with open(out, "w", newline="\n") as f:
    f.write("// Generated by tools/shaders/build.sh from %s. Do not edit.\n" % source)
    f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n")
    for arg in sys.argv[3:]:
        name, path = arg.split("=", 1)
        data = open(path, "rb").read()
        if path.endswith(".metal"):
            data += b"\0"
        f.write("\nalignas(4) static const uint8_t %s[] = {\n" % name)
        for i in range(0, len(data), 16):
            f.write("\t" + ", ".join("0x%02x" % b for b in data[i : i + 16]) + ",\n")
        f.write("};\nstatic const size_t %s_size = sizeof(%s);\n" % (name, name))
