# cmake -DOUT=file.cc -DFILES="a;b;c" -P EmbedAssets.cmake
# Writes a C++ file with spike_embedded_assets[] = { { "basename", data, size }, ... }.
set(body "")
set(table "")
set(i 0)
foreach(f ${FILES})
    get_filename_component(name "${f}" NAME)
    file(READ "${f}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n" bytes "${bytes}")
    string(APPEND body "static unsigned char const asset${i}[] = {\n${bytes}0x00 };\n")
    string(APPEND table "\t{ \"${name}\", asset${i}, ${size} },\n")
    math(EXPR i "${i} + 1")
endforeach()
file(WRITE "${OUT}" "// Generated by src/spike/EmbedAssets.cmake. Do not edit.\n#include <cstddef>\n"
    "struct SpikeEmbeddedAsset { char const* name; unsigned char const* data; size_t size; };\n"
    "${body}\n"
    "extern SpikeEmbeddedAsset const spike_embedded_assets[] = {\n${table}};\n"
    "extern size_t const spike_embedded_asset_count = ${i};\n")
