#include "UiSpike.h"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <sstream>

#define STB_IMAGE_WRITE_STATIC
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

// Generated by CMake (EmbedAssets.cmake): spike_embedded_assets[] = { name, data, size }
struct SpikeEmbeddedAsset { char const* name; unsigned char const* data; size_t size; };
extern SpikeEmbeddedAsset const spike_embedded_assets[];
extern size_t const             spike_embedded_asset_count;

namespace spike {

SaveListModel SaveListModel::Fake(int count)
{
	static char const* const names[] = { "Omerta landing", "Drassen airport taken", "Before the SAM site",
		"Cambria hospital", "Alma mine", "Grumm factory", "Tixa prison break", "Balime museum",
		"Chitzena ruins", "San Mona", "Estoni gas station", "Orta basement", "Meduna outskirts",
		"Palace approach", "Quicksave" };
	static char const* const sectors[] = { "A9 Omerta", "B13 Drassen", "D15 SAM site", "F8 Cambria",
		"I14 Alma", "H3 Grumm", "J9 Tixa", "L11 Balime", "G2 Chitzena", "C5 San Mona", "I6 Estoni",
		"K4 Orta", "N3 Meduna", "P3 Meduna palace", "A10 Omerta" };
	SaveListModel m;
	for (int i = 0; i < count; ++i)
	{
		int const n = i % int(std::size(names));
		SaveSlot s;
		s.name   = names[n];
		if (i >= int(std::size(names))) s.name += " (" + std::to_string(i / int(std::size(names)) + 1) + ")";
		s.sector = sectors[n];
		s.day    = 1 + i * 3;
		s.hour   = (7 + i * 5) % 24;
		s.minute = (i * 17) % 60;
		s.money  = 20000 + i * 7350;
		s.mercs  = 1 + i % 18;
		s.when   = "Day " + std::to_string(s.day) + ", " + std::to_string(s.hour) + ":" + (s.minute < 10 ? "0" : "") + std::to_string(s.minute);
		m.slots.push_back(s);
	}
	return m;
}

void SaveListModel::select(int i)
{
	if (modal) return;
	selected = (i >= 0 && i < int(slots.size())) ? i : -1;
}

void SaveListModel::load()
{
	if (modal || selected < 0) return;
	status = "Loaded \"" + slots[selected].name + "\"";
}

void SaveListModel::askDelete()
{
	if (selected >= 0) modal = true;
}

void SaveListModel::confirmDelete()
{
	if (!modal || selected < 0) return;
	status = "Deleted \"" + slots[selected].name + "\"";
	slots.erase(slots.begin() + selected);
	selected = -1;
	hovered  = -1;
	modal    = false;
}

void SaveListModel::cancel()
{
	if (modal) modal = false;
	else closeRequested = true;
}

std::string SaveListModel::tooltip(int i) const
{
	if (i < 0 || i >= int(slots.size())) return {};
	SaveSlot const& s = slots[i];
	return s.sector + " - " + std::to_string(s.mercs) + (s.mercs == 1 ? " merc" : " mercs") +
		" - double-click to load";
}


static std::string g_overrideDir;

void SetAssetOverrideDir(std::string dir) { g_overrideDir = std::move(dir); }

Blob EmbeddedAsset(std::string const& name)
{
	for (size_t i = 0; i < spike_embedded_asset_count; ++i)
	{
		if (name == spike_embedded_assets[i].name) return { spike_embedded_assets[i].data, spike_embedded_assets[i].size };
	}
	return { nullptr, 0 };
}

std::vector<unsigned char> LoadAssetBytes(std::string const& name)
{
	if (!g_overrideDir.empty())
	{
		std::ifstream f(g_overrideDir + "/" + name, std::ios::binary);
		if (f) return { std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>() };
	}
	Blob const b = EmbeddedAsset(name);
	if (!b.data) throw std::runtime_error("ui spike: no asset " + name);
	return { b.data, b.data + b.size };
}

std::string LoadAssetText(std::string const& name)
{
	auto const bytes = LoadAssetBytes(name);
	return { bytes.begin(), bytes.end() };
}


std::unique_ptr<Screen> CreateScreen(std::string const& kind, SDL_Renderer* r, SaveListModel m)
{
	if (kind == "rml")     return CreateRmlScreen(r, std::move(m));
	if (kind == "inhouse") return CreateInhouseScreen(r, std::move(m));
	throw std::runtime_error("ui spike: unknown toolkit " + kind);
}


bool FindElement(Screen& s, std::string const& id, SDL_FRect& out)
{
	s.update(0);
	for (Element const& e : s.elements())
	{
		if (e.id == id) { out = e.rect; return true; }
	}
	return false;
}

bool ClickElement(Screen& s, std::string const& id)
{
	SDL_FRect r;
	if (!FindElement(s, id, r)) return false;
	float const x = r.x + r.w / 2, y = r.y + r.h / 2;
	s.mouseMove(x, y);
	s.update(1.0 / 60);
	s.mouseButton(x, y, true);
	s.update(1.0 / 60);
	s.mouseButton(x, y, false);
	s.update(0.5); // no double click with the next one
	return true;
}

void ApplyState(Screen& s, std::string const& state)
{
	if (state == "default" || state.empty()) return;
	if (state == "hover")
	{
		ClickElement(s, "slot2");
		SDL_FRect r;
		if (FindElement(s, "slot4", r)) s.mouseMove(r.x + r.w * 0.3f, r.y + r.h / 2);
	}
	else if (state == "scrolled")
	{
		SDL_FRect r;
		if (FindElement(s, "list", r)) s.mouseMove(r.x + r.w / 2, r.y + r.h / 2);
		for (int i = 0; i < 4; ++i) { s.wheel(1); s.update(1.0 / 60); }
		s.mouseMove(-1000, -1000);
	}
	else if (state == "modal")
	{
		ClickElement(s, "slot1");
		ClickElement(s, "delete");
		s.mouseMove(-1000, -1000);
	}
	else
	{
		throw std::runtime_error("ui spike: unknown state " + state);
	}
	s.update(1.0 / 60);
}

OffscreenResult RenderOffscreen(std::string const& kind, int w, int h, int frames,
	std::function<void(Screen&)> const& script)
{
	using clock = std::chrono::steady_clock;
	OffscreenResult res;
	SDL_Surface* surface = SDL_CreateSurface(w, h, SDL_PIXELFORMAT_ARGB8888);
	if (!surface) throw std::runtime_error(SDL_GetError());
	SDL_Renderer* r = SDL_CreateSoftwareRenderer(surface);
	if (!r) throw std::runtime_error(SDL_GetError());
	{
		auto t0 = clock::now();
		auto screen = CreateScreen(kind, r, SaveListModel::Fake());
		screen->setSize(w, h);
		if (script) script(*screen);
		screen->update(1.0 / 60);
		screen->render();
		SDL_FlushRenderer(r); // the software renderer batches until a flush or present
		auto t1 = clock::now();
		res.msFirst = std::chrono::duration<double, std::milli>(t1 - t0).count();
		double total = 0;
		for (int i = 0; i < frames; ++i)
		{
			auto a = clock::now();
			screen->update(1.0 / 60);
			screen->render();
			SDL_FlushRenderer(r);
			total += std::chrono::duration<double, std::milli>(clock::now() - a).count();
		}
		res.msSteady = frames > 0 ? total / frames : 0;
	}
	SDL_DestroyRenderer(r);
	res.surface = surface;
	return res;
}

bool SavePng(SDL_Surface* s, std::string const& path)
{
	SDL_Surface* rgba = SDL_ConvertSurface(s, SDL_PIXELFORMAT_ABGR8888); // bytes R,G,B,A in memory
	if (!rgba) return false;
	for (int y = 0; y < rgba->h; ++y)
	{
		auto* p = static_cast<unsigned char*>(rgba->pixels) + y * rgba->pitch;
		for (int x = 0; x < rgba->w; ++x) p[x * 4 + 3] = 255;
	}
	bool const ok = stbi_write_png(path.c_str(), rgba->w, rgba->h, 4, rgba->pixels, rgba->pitch) != 0;
	SDL_DestroySurface(rgba);
	return ok;
}

} // namespace spike
