#!/usr/bin/env python3
"""Regenerate every raster/platform icon from assets/icons/logo.svg.

    uv run --no-project --with resvg-py --with pillow python tools/gen_logo_icons.py

Writes assets/icons/logo.{png,ico,icns}, src/sgp/Icon.h (the 64x64 window icon), and the Android
launcher icons (legacy mipmaps plus the adaptive-icon foreground and background colour).
"""
import io
import re
from pathlib import Path

import resvg_py
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SVG = ROOT / "assets/icons/logo.svg"
RES = ROOT / "android/app/src/main/res"
BACKGROUND = "#150F08"  # --c-bg


def render(size: int, svg: str | None = None) -> Image.Image:
    png = bytes(resvg_py.svg_to_bytes(svg_string=svg or SVG.read_text(), width=size, height=size))
    return Image.open(io.BytesIO(png)).convert("RGBA")


def window_icon_header(img: Image.Image) -> str:
    data = img.tobytes()
    lines = []
    for i in range(0, len(data), 32):
        lines.append('\t"' + "".join(f"\\{b:03o}" for b in data[i:i + 32]) + '"')
    return (
        "#ifndef ICON_H\n#define ICON_H\n\n"
        "// Generated by tools/gen_logo_icons.py from assets/icons/logo.svg. Do not edit.\n"
        "static const struct {\n\tunsigned int\twidth;\n\tunsigned int\theight;\n"
        "\tunsigned int \tbytes_per_pixel; /* 2:RGB16, 3:RGB, 4:RGBA */\n"
        f"\tunsigned char\tpixel_data[{img.width} * {img.height} * 4 + 1];\n"
        "} gWindowIconData = {\n"
        f"\t{img.width}, {img.height}, 4,\n" + "\n".join(lines) + ",\n};\n\n#endif\n"
    )


def main() -> None:
    icons = ROOT / "assets/icons"
    render(256).save(icons / "logo.png")
    render(256).save(icons / "logo.ico", sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    render(1024).save(icons / "logo.icns")
    (ROOT / "src/sgp/Icon.h").write_text(window_icon_header(render(64)), newline="\n")

    # Android: legacy launcher icons (square on the page colour, and round), then the adaptive foreground,
    # which is the mark scaled into the 72/108 safe zone over a flat background colour.
    for density, size in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        mark = render(size)
        square = Image.new("RGBA", (size, size), BACKGROUND)
        square.alpha_composite(mark)
        square.save(RES / f"mipmap-{density}/ic_launcher.png")
        mark.save(RES / f"mipmap-{density}/ic_launcher_round.png")

    svg = SVG.read_text()
    inner = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    fg = ('<svg xmlns="http://www.w3.org/2000/svg" width="432" height="432" viewBox="0 0 108 108">'
          '<g transform="translate(18 18) scale(0.75)">' + inner + "</g></svg>")
    drawable = RES / "drawable"
    (drawable / "ic_launcher_foreground.xml").unlink(missing_ok=True)
    render(432, fg).save(drawable / "ic_launcher_foreground.png")
    (RES / "values/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n</resources>\n', newline="\n")


if __name__ == "__main__":
    main()
